### ISSUE TITLE
sgx sdk on archlinux

### ISSUE THREAD

**Issue by n0way0ut** [intel/linux-sgx#100]
there is a way to have it on distros different than ubuntu? and in particular archlinux? I tried to install it there, but there are a lot of issues..

**Comment by rodolfoams** [comment]
Currently supported distros are Ubuntu, RHEL Server and CentOS.

**Comment by n0way0ut** [comment]
yes, and it is quite impossible without issues to use it on different distros. Is there a plan to support other distros, or make it more generic?

**Comment by andyzyb** [comment]
As there are so many Linux distros, the focus will be on several of them.  You can try to build the whole SGX software on the distro you are using and see what the issue is.  You can report the issue or submit a PR here.  If it is an easy change, it may be included.

**Comment by deathholes** [comment]
I'm able to install and run sgx sdk on archlinux. Some of the issues that I recall and how I handled them are:
1) some field missing in a kernel data structure ( address field or something): I check the kernel code and found that that specific field was renamed to something else. So changed it to the new one.
2) Some error in aesm_service module (some BIO structure not found): Arch linux uses the latest version of openssl which doesn't have those files in the open(public). So I installed the package "openssl-1.0" from the extra repository and made a temporary link in the /usr/include so that it uses the header files of "openssl-1.0" instead of "openssl-1.1". 
3) installing the bin file for psw throwed an error of "arch command not found". So I changed the command from "arch" to "uname -m"
4) there were some error due to python. Arch linux links 'python' to 'python3' unlike others where it is 'python2'. Changed the code to use python2 explicitly instead of python.

Can't remember anything extra. If you still not able to build it, you can message me.

**Comment by promach** [comment]
@deathholes I am still having [openssl](https://bbs.archlinux.org/viewtopic.php?pid=1885410#p1885410) issue.  Can we use the latest openssl with aesm_service module inside intel sgx ?

**Comment by promach** [comment]
I managed to install both SGX and PSW using these [two PKGBUILDs](https://bbs.archlinux.org/viewtopic.php?pid=1886222#p1886222)

However, I could not [source the environment variables](https://github.com/intel/linux-sgx/blob/master/README.md#install-the-intelr-sgx-sdk-1) required for sgx code compilation.

Why is that so ?

**Comment by promach** [comment]
I tried `[phung@archlinux ~]$ sudo systemctl restart aesmd
 [sudo] password for phung: 
 Failed to restart aesmd.service: Unit aesmd.service not found.
` 

I am not sure if I had done the [psw installation guide](https://github.com/intel/linux-sgx/#install-the-intelr-sgx-psw-1) [correctly](https://bbs.archlinux.org/viewtopic.php?pid=1886604#p1886604).

**Comment by llly** [comment]
For SDK, the environment in the archlinux thread is incorrect. should be 
```
export SGX_SDK=@full path of intalled sdk@/sgxsdk
export PATH=$PATH:$SGX_SDK/bin:$SGX_SDK/bin/x64
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$SGX_SDK/pkgconfig
if [ -z "$LD_LIBRARY_PATH" ]; then
     export LD_LIBRARY_PATH=$SGX_SDK/sdk_libs
else
     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SGX_SDK/sdk_libs
fi
```
you can refer (https://github.com/intel/linux-sgx/blob/master/linux/installer/common/sdk/Makefile) and using `INSTALLER_FORMAT=BIN`.

For PSW, (https://github.com/intel/linux-sgx/blob/master/linux/installer/common/psw/install.sh) is executed to install aesmd.service. These command should be add to package() of PKGBUILD.

**Comment by promach** [comment]
@llly 

If I use the following package() , I will have _error ./install.sh: line 37: ./installConfig: No such file or directory_


```
 package() {

  cd "$srcdir/linux-sgx"

  install -dm 755 "$pkgdir/opt/intel/sgxpsw"
  bsdtar -xf linux/installer/common/psw/output/sgxpsw_1.0.orig.tar.gz -C "$pkgdir/opt/intel/sgxpsw" --strip-components 1 --no-same-owner package

  cd "$srcdir/linux-sgx/linux/installer/common/psw"

  sh ./install.sh
}
```

**Comment by promach** [comment]
and if I use the following package() instead, I will have the following error output:

```
Generated psw installer: ./linux/installer/bin/sgx_linux_x64_psw_2.8.100.3.bin
==> Entering fakeroot environment...
==> Starting package()...
Makefile:32: scripts/installConfig: No such file or directory
make: *** No rule to make target 'scripts/installConfig'.  Stop.
==> ERROR: A failure occurred in package().
    Aborting...
```

```
package() {
  cd "$srcdir/linux-sgx"

  install -dm 755 "$pkgdir/opt/intel/sgxpsw"
  bsdtar -xf linux/installer/common/psw/output/sgxpsw_1.0.orig.tar.gz -C "$pkgdir/opt/intel/sgxpsw" --strip-components 1 --no-same-owner package

  cd "$srcdir/linux-sgx/linux/installer/common/psw"

  make PREFIX="/usr" DESTDIR="$pkgdir" install
}
```

**Comment by llly** [comment]
The Makefile and install.sh cannot be used without modification. If you don't know what to be changed in them, my suggestion is following the README to use bin installer instead of  implementing PKGBUILD.
