### ISSUE TITLE
Remote attestation: Multiple user of enclave. 

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#205]
1. I have a server(with enclave) and multiple clients(non SGX machine) that interact with the server. I could not understand how these multiple clients can use remote attestation to share a secret with the server and confirm that the server's enclave is legitimate.

2. Whose certificate I should submit to IAS. Does each client has to register to IAS or I should give server cert to IAS service registration.

It would be great if anyone could show the communication in this scenario. e.g. at which point the client shares the message with the server.

I am already aware of https://software.intel.com/en-us/articles/intel-software-guard-extensions-remote-attestation-end-to-end-example

**Comment by naishai** [comment]
The usage model is exactly the other way.
The server is not running an enclave, only the clients. The sever is supposed to be in some trusted place.
The enclaves have hard coded server public key with which they verify that they indeed communicating with the server, and they also create an encrypted channel with this key.
The server verify the clients enclaves by communicating with IAS using the certificate it registered with IAS.
I hope that now you can understand the description in the article you linked.

**Comment by gmatesunny** [comment]
Let's talk about the remote attestation example in Linux SGX SDK.
ISV_app : Server enclave
ISV_enclave: Server enclave
SP: Client
1. Now suppose I have multiple SP1 SP2 SP3. So who needs to register for IAS, the SP's or ISV?
2. Does the ISV_app should actually be deployed on a real server so it talks with IAS via the internet.
3. Where should I keep the public certificate of IAS? on each SP or on ISV?

**Comment by rodolfoams** [comment]
Hi, @gmatesunny.
Despite this not being the original usage model, as pointed out by @naishai, SGX can be used in the way you intend to.
So answering the original questions in your first comment:
In the scenario you proposed, each client should register to IAS, sending their own certificate. This certificate will be used when communicating with IAS later on.
The secrets should only be sent by the clients after receiving the confirmation from IAS that the QUOTE received in MSG3 is valid, and that the MRENCLAVE (or MRSIGNER, depending on your policy) is the one expected.

**Comment by gmatesunny** [comment]
Hi @rodolfoams 
So in my scenario, the server actually never directly talks to IAS [1. Yes?]. It is each SP that talks to IAS and the SP should actually keep the keep the public certificate of IAS [2. Yes ?] and while creating the SP cert each SP should provide correct FQDN as it will be used by IAS to communicate with SP [3. Yes?]

**Comment by rodolfoams** [comment]
That's all correct.
Just to make more clear on the third question: when building MSG2, the SP should provide the SPID received from IAS after registration of its certificate. Then, this SPID will be used to build MSG3, and IAS will verify if the certificate the SP uses to communicate with it matches the SPID used to build MSG3.

**Comment by gmatesunny** [comment]
Hi, 

While reading more about remote attestation, I wonder in my case of multiple clients, how attestation will prove the authenticity/identity of the enclave? Whose private key should be used to sign the enclave? 
Also, https://software.intel.com/sites/default/files/managed/7e/3b/ias-api-spec.pdf  says **It is the responsibility of the Service Provider to validate the ISV enclave identity.** What should I do it in my case? Do I have to share the private key used to sign the enclave with all the user?

**Comment by rodolfoams** [comment]
Hi,
as mentioned before, each enclave has two identities: MRENCLAVE and MRSIGNER.
The private key used to sign the enclave will have direct influence in its MRSIGNER identity. The MRENCLAVE identity is influenced by the actual code+libs of the enclave.
Now back to your questions:

> how attestation will prove the authenticity/identity of the enclave?
The response from IAS will tell you if the QUOTE sent to it has been generated in a genuine SGX enclave. IAS does this by verifying the QUOTE signature that was created using the EPID key.

> Whose private key should be used to sign the enclave?
The enclave developer's private key should be used here.

> Also, https://software.intel.com/sites/default/files/managed/7e/3b/ias-api-spec.pdf says It is the responsibility of the Service Provider to validate the ISV enclave identity. What should I do it in my case?
What this means is that IAS verifies the authenticity of the QUOTE, but it doesn't what was the MRENCLAVE or MRSIGNER that was expected by your application (your clients in this case), therefore you must verify if the enclave identity is the one you expected (again, your clients should check this).

> Do I have to share the private key used to sign the enclave with all the user?
NEVER share your private key with anyone! This would allow an attacker to create a rogue application and say that it was developed by you.

> Who has the hash of the enclave?
The developer of the enclave should publish its identities, so that clients can successfully verify it in the last step of the remote attestation process.

> what is the role of the private key used to sign the enclave?
Already answered that one. in the beginning.

**Comment by gmatesunny** [comment]
Super, loved it.
