### ISSUE TITLE
aesmd can't start with ref_le

### ISSUE THREAD

**Issue by light1021** [intel/linux-sgx#206]
Hi:
I want to try ref_le, but when I build psw with ref_le **aesmd** can not start. What's "the platform must support the Flexible Launch Control (FLC) feature" mean ? How can I determine whether my platform support this feature or not?  And it seems that ref_le only works with in kernel sgx driver, because it tries to stat device /dev/sgx, is that right ?

**Comment by haimcn** [comment]
Flexible Launch Control enables using different LE that is not signed by Intel.
Sections 38.1.4 and 41.2.2 of the SDM are describing the Launch Control configuration, in the latter you can see that CPUID.(EAX=07H, ECX=00H):ECX[30] specifies whether the platform supports FLC and BIOS must enable FLC in IA32_FEATURE_CONTROL.LE_WR (bit 17).
Both conditions must be met in order to use LE not signed by Intel (and setting the IA32_SGXPUBKEYHASH0..3 MSRs), see also the ref_le readme.

ref_le does not require in-kernel driver, this release of PSW supports both in-kernel driver and out-of-tree driver, it is orthogonal to the LE being used.

**Comment by light1021** [comment]
Unfortunately, Both my NUCi7BNH and Dell Inspiron 7460 doesn't support that feature. I test it with cpuid.(EAX=7, ECX=0), But returned ECX is 0x0.  Is there any known platform that supports this feature ? I think , in some case, this is a useful feature.

**Comment by haimc-intel** [comment]
Flexible Launch Control will be supported in future platforms.

**Comment by light1021** [comment]
Oh！ I am sorry to hear that. I noticed that kvm-sgx also have this Flexible Launch Control feature. Is this feature works on a kvm-sgx meachine now ?

**Comment by andyzyb** [comment]
Flexible Launch Control depends on hardware and BIOS while kvm-sgx may not help on a platform which doesn't support it.
