### ISSUE TITLE
Intel SGX developer license and open-source software signing

### ISSUE THREAD

**Issue by imlibra** [intel/linux-sgx#228]
Is it possible to obtaining a licensed developer certificate for signing security-reviewed, community-developed open source SGX software binary in production mode, and publish it on open source repository like apt or rpm?

Currently, there are no way to run open-source SGX software with production mode, it makes Intel SGX a commercial-only environment.

**Comment by haitaohuang** [comment]
Your question is not clear to me. Let me try to clarify some terms used here. Open source is a development model for people to collaborate with you at source code level. Publishing final released binary into apt or rpm repositories requires you to have agreement/arrangement with distros Ubuntu, RH, which is not SGX related.

For Intel SGX enclaves, you can certainly develop in open source if you choose so.  To run a production enclave on production Intel hardware, you do need sign enclave with a private key that's only available to you, and obtain certificate from Intel so that your public key is whitelisted.   (Others using your open source code to create their own enclaves would have to do so too)

During development, you can freely test enclave in debug mode. 

So I don't think the license agreement restrict you from  developing open source solution.  But if you have decided that you have a production enclave based on open source code to run on production hardware,  follow process described in here to get proper license:https://software.intel.com/en-us/sgx/commercial-use-license-request.

And any specific licensing issues, please contact formal channels described in above link.

**Comment by imlibra** [comment]
What if I need to run open source software contributes by myself or others in production mode for my own data protection?

**Comment by haitaohuang** [comment]
Currently, you need sign enclave and get your public keys whitelisted. But again, this has nothing to do with whether you do open source or not in my opinion. Also "data protection" is a loaded term. You may need more than just running enclave to really protect your data, e.g. remote attestation for your enclave.

For just running the enclave:

Only Intel signed Launch Enclave can generate valid launch token for enclaves to run on production CPUs public available at the moment. In future platforms with SGX enabled kernel, it is possible for others to use default launch enclave in kernel, which controls launch policy, which is permissive by default. However, the kernel patches are not yet reviewed and integrated into kernel main line yet. See https://github.com/intel/linux-sgx/issues/200.
