### ISSUE TITLE
Local Attestation

### ISSUE THREAD

**Issue by khanhct-viosoft** [intel/linux-sgx#243]
Hi Intel,
I have some questions and need you to clarify. 
I want to communicate two enclaves between two different applications (Server and client Model)  and I referred Local Attestation at https://software.intel.com/en-us/node/702983  However,  I can't create session between two enclaves. Then, I search on the Internet to verify this model.
ENCLAVE A <------------------------------>ENCLAVE B
APPLICATION A <------------------------->APPLICATION B

 I saw a post on Intel Forum about Local attestation of enclaves from different applications: https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/707074 . Currently, I am confusing between two posts. They almost opposed . Please help me to clarify that. 
Thank for your support!

**Comment by naishai** [comment]
Hi,
Local attestation is used for establishing a secure communication channel between two enclaves running on the same machine.
Remote attestation is used for establishing a secure communication channel between enclave and a remote server, only the client need to be an enclave, the remote machine is assumed to be the 'trusted' part. The rational is that the server is providing some secret to the enclave, and it wants to verify that indeed it is a valid enclave before handing over the secret. The server contacts Intel Attestation Server to verify that the enclave's signature is indeed up-to-date and that the key used is still valid.
An example exist here: https://software.intel.com/en-us/articles/intel-software-guard-extensions-remote-attestation-end-to-end-example

**Comment by khanhct-viosoft** [comment]
Thank @naishai 
" Local attestation is used for establishing a secure communication channel between two enclaves running on the same machine." ===> it is possible if two enclaves are in two different applications. If yes. Can you share me an example to prove this?

**Comment by naishai** [comment]
Hi, you can check the code in the sdk which creates a session with the platform services enclave (local attestation between any application using the sdk and the local intel ae service), it is in sdk/tae_service/tae_service.cpp

**Comment by hyjiang** [comment]
Local attestation is using an updated ECDH protocol, which includes enclave's report. It requires all enclaves on same platform, otherwise, an enclave cannot verify another enclave's report.

If you want to establish the secure channel between two processes, I suppose you need to add some logics to help to transfer message. Such as ECALL

*************************************************************************************
sgx_status_t SGXAPI sgx_dh_initiator_proc_msg1(const sgx_dh_msg1_t* msg1,
                                               sgx_dh_msg2_t* msg2,
                                               sgx_dh_session_t* dh_session);
*************************************************************************************

You need to get msg1 from another process first, then send msg2 to another process. Also, you need to remember dh_session in 2 processes.

**Comment by XunMrh** [comment]
Hi,@khanhct-viosoft. I`m thinking about this model recently. Have you solved it? And would you like to provide an example. Thank you.

**Comment by jsraynor** [comment]
FYI, if this is still of interest to some folks...

https://sgx101.gitbook.io/sgx101/sgx-bootstrap/attestation/inter-process-local-attestation
https://github.com/sangfansh/SGX101_sample_code/tree/master/ProcessLocalAttestation

Regards.

Scott
