### ISSUE TITLE
Interaction required for remote attestaton

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#269]
I do not need to create secure channel to provision secret to enclave but I wanted to perform remote attestation of my server(sgx enabled) from my client(non sgx). Do I still need to perform all steps like msg0, msg1 and etc between client and server. 

The client and server already talks over ssl/tls created using mbedtls-sgx (https://github.com/bl4ck5un/mbedtls-SGX) via custom REST APIs

**Comment by jmechalas** [comment]
Yes, you do.

Msg0 is how the attestation proxy learns what the client's Extended EPID GID is (this should be 0).

Msg1 is how the server learn's the client's public session key, so that it can derive its own session key to send to the client (as part of Msg2), so that the two of them can derive a shared secret.

Skip any of these, and you aren't really doing remote attestation as intended (and, in fact, you _can't_ do it on the client side using the convenience functions sgx_ra_get_msg1 and sgx_ra_proc_msg3).

You can send Msg0 and Msg1 at the same time, however, by concatenating them together.

**Comment by sqq0216** [comment]
we can get the sgx_ec256_public_t  by call sgx_ra_get_msg1, but I want to know  what is the corresponding private key of sgx_ec256_public_t  g_a, and how can I get it ,I want to use the private key to sign something and use the public key to verify signature.

**Comment by jmechalas** [comment]
It is intentionally not exposed as it is an ephemeral session key. If you wish to sign something, I'd suggest generating a key inside the enclave and exporting the public key to the untrusted application. You can use data sealing to write the private key to disk if you need persistence.

**Comment by sqq0216** [comment]
Thanks for your suggestion，but based on my previous study，I think if there is a public key，must have a private key to use，if it is nor exposed ，what  is the purpose to use the public key at remote attestation's msg1?

**Comment by jmechalas** [comment]
It's part of a DH key exchange. The public key is sent to the relying party (the server that the client is attesting to), and the relying party uses it to derive a shared secret. See the document, [Intel® Software Guard Extensions Remote Attestation End-to-End Example](https://software.intel.com/content/www/us/en/develop/articles/code-sample-intel-software-guard-extensions-remote-attestation-end-to-end-example.html).
