### ISSUE TITLE
How to use OpenMP within the Enclave

### ISSUE THREAD

**Issue by william-gallagher** [intel/linux-sgx#531]
Hi,

I am looking for some guidance on how to use OpenMP within the SGX Enclave. I am trying to use OpenMP for matrix multiplication as shown in the code below.

```C
void gemm(int M, int N, int K, float ALPHA, 
        float *A, int lda, 
        float *B, int ldb,
        float *C, int ldc)
{
    int i,j,k;

    #pragma omp parallel for
    for(i = 0; i < M; ++i){
        for(k = 0; k < K; ++k){
            float A_PART = ALPHA*A[i*lda+k];
            for(j = 0; j < N; ++j){
                C[i*ldc+j] += A_PART*B[k*ldb+j];
            }
        }
    }
}
```

I see that the Linux 2.8 Open Source Gold Release of January 2020 has added support for OpenMP. The only example I can find to using OpenMP within an Enclave is in the Deep Neural Network Library that was added in the same release. My examination of the Makefile associated with that project shows adding the -lsgx_omp flag to the Enclave_Link_Flag variable. I have done the same. Here is part of my Enclave_Link_Flag variable in my Makefile.

```Makefile
-Wl,--start-group -lsgx_tstdc -lsgx_pthread -lsgx_omp -lsgx_tcxx -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group \
```
My project builds and runs without errors. Using OpenMP leads to performance gains of about 3x when running the segment of code shown above outside the Enclave with large matrices. I see no performance gain with OpenMP when running in the Enclave. This leads me to believe that I have not properly enabled OpenMP within the Enclave. Any help on this would be greatly appreciated. 

I believe that it is not possible for a thread running inside an Enclave to create other threads inside the Enclave. If so, how does OpenMP work? I have played with the thread settings in the Enclave configuation file. Using the same settings as the DNNL project has not helped:

```xml
  <TCSNum>6</TCSNum>
  <TCSMinPool>16</TCSMinPool>
  <TCSMaxNum>32</TCSMaxNum>
  <TCSPolicy>1</TCSPolicy>
```
Again any help is appreciated.
Thanks,
Will

**Comment by lzha101** [comment]
Firstly, your operation to use OpenMP inside enclave is correct if you also put `-fopenmp` option to the enclave compiling options.
 
SGX OpenMP is a customized version based on LLVM OpenMP, by applying the patch (https://github.com/intel/linux-sgx/blob/master/external/openmp/0001-Enable-OpenMP-in-SGX.patch ).  So It still needs to create working threads inside enclave. As you know, we released a SGX Pthread library as well when we released SGX OpenMP.  SGX OpenMP depends on SGX Pthread library for thread management. 

Due to SGX Enclave's limitation, the behavior for SGX OpenMP indeed has some difference from the OpenMP outside.  Suppose below factors are related to the performance:
1. Working threads number are not only related to CPU core but also related to TCS Number.
2. Each working thread creating needs to ocall outside and ecall back. 
3. Threads waking up and waiting also needs to ocall and ecall back. 

So if the calculation you want to parallelized perform is not that complicated, the performance may not be improved because ecall/ocall introduces much performance loss.

**Comment by andyzyb** [comment]
One another angle for performance is how big your enclave is and how much EPC memory available on your system.   If the enclave size is much bigger than EPC memory then paging may occur frequently inside Enclave, while it is not outside Enclave.

**Comment by william-gallagher** [comment]
Thank you for your help. Adding the -fopenmp to my Enclave compiling options is what I was missing. I can see the performance boost I was missing before. You are correct in anticipating that the performance increase is not as great as running the same code outside the Enclave. I am attributing this to the overhead of the ecalls and ocalls. I believe that the sizes I am working with are below the threshold to trigger paging as the EPC is set at 110 MiB. 
Again, your help is greatly appreciated.
Will
