### ISSUE TITLE
Please include header file for IPP SGX Dispatcher functions

### ISSUE THREAD

**Issue by ENOTTY** [intel/linux-sgx#728]
All of the functions in `sdk/tlibcrypto/ipp/ipp_disp` seem pretty useful, dispatching between CPUs with different features. Unfortunately there is no header file for them.

Including `ipp/sgx_ippcp.h` in code for an SGX enclave will rewrite all previous usages of IPP functions with no corresponding header, leader to a broken build.

**Comment by lzha101** [comment]
Are you directly including the `sgx_ippcp.h` to your enclave code? If this is the case, try to include the `ippcp.h`  from SGX SDK in your enclave code instead of `sgx_ippcp.h`.
`sgx_ippcp.h` just includes some function renaming things and will be included in the `ippcp.h`.  This makes the IPP function to use the dispatch wrapper in the `ipp_disp`.

**Comment by ENOTTY** [comment]
Thanks, I think that worked!
