### ISSUE TITLE
Thread local storage issue in SGX Simulation sdk >= 2.15

### ISSUE THREAD

**Issue by amper-fb** [intel/linux-sgx#758]
There seems to be an issue with TLS initialization since sdk version 2.15, doesn't reproduce with sdk version 2.13.3.1

Sample Repo:

https://github.com/amper-fb/linux-sgx/tree/tls/SampleCode/Cxx14SGXTLS

Steps to reproduce:
```
1. Install Intel(R) Software Guard Extensions (Intel(R) SGX) SDK for Linux* OS
2. Make sure your environment is set:
$ source ${sgx-sdk-install-path}/environment

3. Clone the sample:
$ git clone https://github.com/amper-fb/linux-sgx/
$ git checkout tls
$ cd SampleCode/Cxx14SGXTLS

4. Build the project with the prepared Makefile in Simulation mode:
$ make SGX_MODE=SIM

5. Execute the binary directly:
$ ./app
```

Expected behavior:
Trusted lib thread local var ([_vec](https://github.com/amper-fb/linux-sgx/blob/b4588e546bc76daa1c8a7517943e7b7e44fbe1a4/SampleCode/Cxx14SGXTLS/Enclave/TrustedLibrary/Libcxx.cpp#L44)) is initialized to NULL during ecall and program exits successfully.

Actual behavior:
Trusted lib thread local var is ([_vec](https://github.com/amper-fb/linux-sgx/blob/b4588e546bc76daa1c8a7517943e7b7e44fbe1a4/SampleCode/Cxx14SGXTLS/Enclave/TrustedLibrary/Libcxx.cpp#L44)) uninitialized during ecall and assertion error is thrown.

Interesting enough, I observed that if you remove the thread_local variable outside the enclave ([_ctx](https://github.com/amper-fb/linux-sgx/blob/b4588e546bc76daa1c8a7517943e7b7e44fbe1a4/SampleCode/Cxx14SGXTLS/App/TrustedLibrary/Libcxx.cpp#L51)) the issue doesn't reproduce.

**Comment by xxu36** [comment]
Hi, I can reproduce your issue. In the Makefile,  `Enclave_C_Flags` contains `-fpie` and `Enclave_Link_Flags` contains `-Wl,-pie`, this kind of combination will lead to a TLS variable access mode that we cannot support in simulation. (BTW, HW mode support it). In 2.13 release, we introduced a change that addressed this issue but we reverted it in release 2.15 since it introduced some other issue.

As a work around, in order to pass your sample, you can consider to use `-fpic` in `Enclave_C_Flags`, which will lead to a TLS access mode supported by SIM.

**Comment by amper-fb** [comment]
Thanks, I can confirm your suggested workaround is working for me.
