### ISSUE TITLE
TCSPolicy and pthread TLS interaction

### ISSUE THREAD

**Issue by henrywang8atfbdotcom** [intel/linux-sgx#842]
Let's say we have the following trusted codes.

```
// Lifetime throughout enclave.
static pthread_key_t key;

// May be re-init on root Ecall.
thread_local long tl = 0;

int ecall_set_val(long val) {
  tl = val;
  long* p = malloc(sizeof(long));
  *p = val;
  pthread_key_create(&key, free);
  pthread_setspecific(key, p) ;
  return 0;
}

long ecall_get_val() {
  long* p = (long*)pthread_getspecific(key);
  if (p == NULL) {
    return 0;
  } else {
    return *p;
  }
}

long ecall_get_thread_local() {
  return tl;
}
```

And in the main driver code.
```
ecall_set_val(100);
r1= ecall_get_val();
r2 = ecall_get_thread_local();
```

Currently, we see the following values of r1, r2 depending on TCS Policy.
Binding: r1 = 0, r2 = 100
Nonbinding: r1 = 0, r2 = 0

Is this expected? The documentation only mentions that Thread Local Storage (implemented with __thread) re-initialization on ecall is dictated by setting TSC Policy = 1. What about the Pthread TLS implementation? Should the value stored by some pthread TLS key persist across root Ecalls?

**Comment by lzha101** [comment]
Submitted a PR to fix this. I think the expected result should be:

Binding: r1 = 100, r2 = 100
Nonbinding: r1 = 0, r2 = 0

**Comment by gilanghamidy** [comment]
Be careful with using `thread_local` on non-trivial object. Because the current Intel SGX SDK **does not provide an implementation of `__cxa_thread_atexit` which is a required C++ ABI for thread_local**. The suggestion provided in this long-running open issue #454 will actually create **memory leak** because the destructor of the non-trivial object will never be called. Thus, the `thread_local` implementation inside the enclave does not adhere **both** C++ semantics as well as the TLSPolicy.

The fix provided by #843 is **not going to fix this** as it only handles the `pthread_tls` case.

**Comment by henrywang8atfbdotcom** [comment]
I think I meant to use `__thread` in the example.

**Comment by lzha101** [comment]
Yes. I also used the `__thread` for verifying the PR #843. 
Now the PR has been merged.  If no additional issue, I think we can close this issue.
