### ISSUE TITLE
replacement for `sgx_get_ps_cap` (removed since release 2.8)

### ISSUE THREAD

**Issue by alreadydone** [intel/linux-sgx#853]
Hello, 

I am trying to compile a two-year old [SGX application](https://github.com/ndokmai/sgx-genome-variants-search) but got errors saying that `sgx_ps_cap_t` and `sgx_get_ps_cap` were not declared. I looked into the history of this repo and found that they were removed [since release 2.8](https://github.com/intel/linux-sgx/commit/9ddec08fb98c1636ed3b1a77bbc4fa3520344ede#diff-3d2d945c0f6b58827e6644eb52a5565cb0ad54077db889fb26b9569113a980eb), as is confirmed by [the release notes](https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.8-release), but there is no clue about why it's deprecated and what it should be replaced with. The same is true for the [2.8 developer reference](https://download.01.org/intel-sgx/sgx-linux/2.8/docs/Intel_SGX_Developer_Reference_Linux_2.8_Open_Source.pdf), where the function `sgx_get_ps_cap` is not mentioned, even though it's documented in the 2.7 reference. So how could I replace the `sgx_get_ps_cap` call in the code to make it compile again?

Thanks in advance for your help!

**Comment by llly** [comment]
It's deprecated because the Platform service capabilities  in `sgx_ps_cap_t` depend on Intel Management Engine (Intel ME), which is not included in Intel server platforms. It's removed and no replacement.
You can remove the function `sgx_get_ps_cap`, `close_session_ocall`, `create_session_ocall`, `exchange_report_ocall`, `invoke_service_ocall` calls and checks from code, Makefile, etc. 
By the way, `libsgx_uae_service.so` is also deprecated now, replaced by `libsgx_launch.so.1`, `libsgx_epid.so.1` and `libsgx_quote_ex.so.1` . Please refer latest sample code.

**Comment by alreadydone** [comment]
Thanks for the reply and the information. I'll check whether removing the calls breaks anything.
