### ISSUE TITLE
cp: cannot stat 'external/toolset/{current_distr}/as'

### ISSUE THREAD

**Issue by siyukok** [intel/linux-sgx#976]
Hello, I am trying to build the "Prerequisites" part on Ubuntu 18.04. I have finished the cd linux-sgx && make preparation
But when I tried 
`sudo cp external/toolset/{current_distr}/* /usr/local/bin`
I found that there is no ubuntu18.04 in the toolset directory. How can I solve this?
the screenshot is here
![image](https://github.com/intel/linux-sgx/assets/21030561/82cc696c-2754-4d9e-b971-aa5217500beb)

**Comment by lzha101** [comment]
You are right. The Ubuntu 18.04 toolset was removed from the toolset package since 2.18 release by mistake. But you can find the Ubuntu 18.04 toolset from https://download.01.org/intel-sgx/sgx-linux/2.17/as.ld.objdump.r4.tar.gz. 

BTW, since Ubuntu 18.04 has been EOL, Ubuntu 18.04 support will be dropped from next SGX release.

**Comment by siyukok** [comment]
Ok,i understand.Thank you for your time.

**Comment by lzha101** [comment]
The issue was fixed in the related impact releases on download.01.org. We updated the toolset packages to include Ubuntu 18.04. Thanks.

**Comment by LNJUSMART** [comment]
Excuse me, I found that there is also no centos 7.9 in the toolset directory. How do I fix this?
